# Generated by Django 4.1.3 on 2023-03-28 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 14, 0, 48, 74451)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 14, 0, 48, 74451)),
        ),
    ]
