# Generated by Django 4.1.3 on 2023-03-28 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 14, 42, 37, 664249)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 14, 42, 37, 664249)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_booking', to='resort.rooms'),
        ),
    ]
